singleServerConfig:
  address: "redis://redis-18995.c135.eu-central-1-1.ec2.redns.redis-cloud.com:18995"
  username: default
  password: Rm8Mi1kNmxxiBDVxcLwTUsb85XG0smzW
  connectionMinimumIdleSize: 4
  connectionPoolSize: 16
  subscriptionConnectionPoolSize: 2
  idleConnectionTimeout: 30000 #ms

